name: '27519'
'on':
  schedule:
    - crone: 0 8 * * *
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: npm install
        env:
          CI: true
      - name: lint
        run: npm run lint --if-present
      - name: generate constants
        run: npm run constants -- --zip=27519
      - name: generate list
        run: npm run list -- --zip=27519
      - name: generate main
        run: npm run main -- --zip=27519
      - name: sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
      - name: generate README.md
        run: npm run readme
      - name: git set user.email
        run: git config --global user.email "xgirma@gmail.com"
      - name: git set user.name
        run: git config --global user.email "Girma Nigusse"
      - name: git status
        run: git status
      - name: git add
        run: git add --all
      - name: git commit
        run: git commit -am "generate data for 27519"
      - name: commit data
        run: git push
