name: 'Cary, 27513, NC :'
'on':
  push: null
  schedule:
    - cron: 0 4 * * *
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: npm install
        env:
          CI: true
      - name: lint
        run: npm run lint --if-present
      - name: count the number of listing pages for 27513
        run: npm run pages -- --zip=27513
      - name: scrap links for all listings within 27513
        if: always()
        run: npm run links -- --zip=27513
      - name: scrap details for all houses in 27513
        if: always()
        run: npm run houses -- --zip=27513
      - name: sleep for 10s
        if: always()
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
      - name: >-
          classify 27513 data into for sale, coming soon, sale pending, and in
          contract
        if: always()
        run: npm run classify -- --zip=27513
      - name: sleep for 10s
        if: always()
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
      - name: 'classify 27513 data into price reduced, open house, and listed today'
        if: always()
        run: 'npm run classify:sale -- --zip=27513'
      - name: sleep for 10s
        if: always()
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
      - name: generate summary data for 27513
        if: always()
        run: npm run summary
      - name: sleep for 10s
        if: always()
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
      - name: sort data for 27513 by price
        if: always()
        run: npm run byprice -- --zip=27513
      - name: sleep for 10s
        if: always()
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
      - name: sort data for 27513 by size
        if: always()
        run: npm run bysize -- --zip=27513
      - name: sleep for 10s
        if: always()
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
      - name: sort data for 27513 by year
        if: always()
        run: npm run byyear -- --zip=27513
      - name: sleep for 10s
        if: always()
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
      - name: sort data for 27513 by days
        if: always()
        run: npm run bydays -- --zip=27513
      - name: sleep for 10s
        if: always()
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
      - name: plot svg chart for 27513
        if: always()
        run: npm run chart -- --zip=27513
      - name: sleep for 10s
        if: always()
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
      - name: generate README.md
        if: always()
        run: npm run readme
      - name: git set user.email
        if: always()
        run: git config --global user.email "xgirma@gmail.com"
      - name: git set user.name
        if: always()
        run: git config --global user.email "Girma Nigusse"
      - name: git set rebase false
        if: always()
        run: git config pull.rebase false
      - name: git pull
        if: always()
        run: git pull
      - name: git status
        if: always()
        run: git status
      - name: git add
        if: always()
        run: git add --all
      - name: git commit
        if: always()
        run: git commit -am "generate data for 27513"
      - name: commit data
        if: always()
        run: git push
