name: moveto 27560
'on':
  schedule:
    - cron: 5 10 * * *
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 'npm:install'
        run: npm install
        env:
          CI: true
      - name: lint
        run: npm run lint --if-present
      - name: constants-Morrisville
        run: npm run constants -- --zip=27560
      - name: list-Morrisville
        run: npm run list -- --zip=27560
      - name: main-Morrisville
        run: npm run main -- --zip=27560
      - name: sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
         time: 10s
      - name: commit data
        run: |
          git config --global user.email "xgirma@gmail.com"
          git config --global user.name "Girma Nigusse"
          git status
          git add --all
          git commit -am "generated 27560"
          git push
