name: moveto
'on':
  push: null
  schedule:
    - cron: 5 3 * * *
jobs:
  build:
    runs-on: macos
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 'npm:install'
        run: npm install
        env:
          CI: true
      - name: lint
        run: npm run lint --if-present
      - name: constants
        run: npm run constants
