name: moveto
'on':
  push: null
  schedule:
    - cron: 5 3 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 'install:linux:dep'
        run: >
          sudo apt-get update

          sudo apt-get install libwoff1 libopus0 libwebp6 libwebpdemux2
          libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0
          libgdk-pixbuf2.0-0 libegl1 libgles2 libevent-2.1-6 libnotify4
          libxslt1.1

          sudo apt-get install xvfb
      - name: 'npm:install'
        run: npm install
        env:
          CI: true
      - name: lint
        run: npm run lint --if-present
      - name: constants
        run: npm run constants
      - name: Commit changes
      - uses: EndBug/add-and-commit@v4
        with:
          author_name: Your Name
          author_email: e2eboilerplate@gmail.com
          message: "updates"
          add: "*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

